{
  "formatVersion": "1.1",
  "component": {
    "group": "TracePlugin",
    "module": "TracePluginDetail",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "TracePluginDetail-unspecified.jar",
          "url": "TracePluginDetail-unspecified.jar",
          "size": 2896,
          "sha512": "c41a804719aae6eef8190a906cfb08a4b0d99d61b97705d2452bafd8be9fce4648a0f4895a21fd5e31482ece5d6f11e2167b36ec7f0c3e221f4fb68f7038c94c",
          "sha256": "7bd85b351f46fff2a6f4c25c2c998811df8003aece57b73576182a4bb0c10746",
          "sha1": "3ce6ec87a8ce56e8c25fc5c968863d380db33f69",
          "md5": "fde535e048a97db7189253cb85838786"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "TracePluginDetail-unspecified.jar",
          "url": "TracePluginDetail-unspecified.jar",
          "size": 2896,
          "sha512": "c41a804719aae6eef8190a906cfb08a4b0d99d61b97705d2452bafd8be9fce4648a0f4895a21fd5e31482ece5d6f11e2167b36ec7f0c3e221f4fb68f7038c94c",
          "sha256": "7bd85b351f46fff2a6f4c25c2c998811df8003aece57b73576182a4bb0c10746",
          "sha1": "3ce6ec87a8ce56e8c25fc5c968863d380db33f69",
          "md5": "fde535e048a97db7189253cb85838786"
        }
      ]
    }
  ]
}
